### ISSUE TITLE
--pythonplugin option does not work 

### ISSUE THREAD

**Issue by faseehahmad** [hexhex/manual#1]
I am trying to run python plugin examples given in the manual but that does not seem to work in my case. I ran the following command as given in the user guide

$ dlvhex2 --pythonplugin=example_2_1.py example_2_1.hex

I received the following usage error

UsageError: Fatal: Unknown option(s): --pythonplugin=example_2_1.py

Why am I getting this error?

**Comment by peschue** [comment]
Please use dlvhex2 --help to see the options. Maybe we have a typo in the
manual and it should be --python-plugin=...

(Sent from the phone.)

Best
Peter

**Comment by peschue** [comment]
Another possibility is that you compiled dlvhex2 without python support.
Again, "dlvhex2 --help" will show you python options if python support is
present.

**Comment by faseehahmad** [comment]
I think i did not compile it with Python support. Thank you so much

Regards

**Comment by peschue** [comment]
In that case I will close the issue. Feel free to re-open it or create a new one if you have problems.

Best,
Peter
